package com.xy9860.shop.model;
// Generated 2017-3-16 19:35:17 by Hibernate Tools 5.2.1.Final

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Integer cid;
	private String ctype;
	private Boolean chot;
	private Account account;

	public Category() {
	}

	public Integer getCid() {
		return cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}

	public String getCtype() {
		return ctype;
	}

	public void setCtype(String ctype) {
		this.ctype = ctype;
	}

	public Boolean getChot() {
		return chot;
	}

	public void setChot(Boolean chot) {
		this.chot = chot;
	}

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Override
	public String toString() {
		return "Category [cid=" + cid + ", ctype=" + ctype + ", chot=" + chot + "]";
	}

	public Category(Integer cid, String ctype, Boolean chot) {
		super();
		this.cid = cid;
		this.ctype = ctype;
		this.chot = chot;
	}

	public Category(String ctype, Boolean chot) {
		super();
		this.ctype = ctype;
		this.chot = chot;
	}

	
}
