package com.xy9860.shop.model;
// Generated 2017-3-22 11:18:04 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import java.util.TreeSet;

/**
 * Forder generated by hbm2java
 */
public class Forder implements java.io.Serializable {

	private Integer fid;
	private String fname;
	private String fphone;
	private String fremark;
	private Date fdate;
	private BigDecimal ftotal;
	private String fpost;
	private String faddress;
	private Status status;
	private User user;
	private Set<Sorder> sorders=new TreeSet<Sorder>();//记得创建实体
	
	public Forder() {
	}

	public Forder(String fname, String fphone, String fremark, Date fdate, BigDecimal ftotal, String fpost,
			String faddress) {
		this.fname = fname;
		this.fphone = fphone;
		this.fremark = fremark;
		this.fdate = fdate;
		this.ftotal = ftotal;
		this.fpost = fpost;
		this.faddress = faddress;
	}

	public Integer getFid() {
		return this.fid;
	}

	public void setFid(Integer fid) {
		this.fid = fid;
	}

	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	public String getFphone() {
		return this.fphone;
	}

	public void setFphone(String fphone) {
		this.fphone = fphone;
	}

	public String getFremark() {
		return this.fremark;
	}

	public void setFremark(String fremark) {
		this.fremark = fremark;
	}

	public Date getFdate() {
		return this.fdate;
	}

	public void setFdate(Date fdate) {
		this.fdate = fdate;
	}

	public BigDecimal getFtotal() {
		return this.ftotal;
	}

	public void setFtotal(BigDecimal ftotal) {
		this.ftotal = ftotal;
	}

	public String getFpost() {
		return this.fpost;
	}

	public void setFpost(String fpost) {
		this.fpost = fpost;
	}

	public String getFaddress() {
		return this.faddress;
	}

	public void setFaddress(String faddress) {
		this.faddress = faddress;
	}

	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Set<Sorder> getSorder() {
		return sorder;
	}

	public void setSorder(Set<Sorder> sorder) {
		this.sorder = sorder;
	}



}
