package com.xy9860.shop.model;
// Generated 2017-3-16 19:35:17 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Product generated by hbm2java
 */
public class Product implements java.io.Serializable {

	@Override
	public String toString() {
		return "Product [pid=" + pid + ", pname=" + pname + ", price=" + price + ", pic=" + pic + ", premark=" + premark
				+ ", pxremark=" + pxremark + ", pdate=" + pdate + ", pcommend=" + pcommend + ", popen=" + popen + "]";
	}

	private Integer pid;
	private String pname;
	private BigDecimal price;
	private String pic;
	private String premark;
	private String pxremark;
	private Date pdate;
	private Boolean pcommend;
	private Boolean popen;
	private Category category;

	public Product() {
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public String getPic() {
		return pic;
	}

	public void setPic(String pic) {
		this.pic = pic;
	}

	public String getPremark() {
		return premark;
	}

	public void setPremark(String premark) {
		this.premark = premark;
	}

	public String getPxremark() {
		return pxremark;
	}

	public void setPxremark(String pxremark) {
		this.pxremark = pxremark;
	}

	public Date getPdate() {
		return pdate;
	}

	public void setPdate(Date pdate) {
		this.pdate = pdate;
	}

	public Boolean getPcommend() {
		return pcommend;
	}

	public void setPcommend(Boolean pcommend) {
		this.pcommend = pcommend;
	}

	public Boolean getPopen() {
		return popen;
	}

	public void setPopen(Boolean popen) {
		this.popen = popen;
	}

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	

}
