package com.xy9860.shop.model;
// Generated 2017-3-22 11:18:04 by Hibernate Tools 5.2.1.Final

import java.math.BigDecimal;

/**
 * Sorder generated by hbm2java
 */
public class Sorder implements java.io.Serializable {

	private Integer sid;
	private String sname;
	private BigDecimal sprice;
	private int snumber;
	private Integer pid;
	private Product product;

	public Sorder() {
	}

	public Sorder(int snumber) {
		this.snumber = snumber;
	}

	public Sorder(String sname, BigDecimal sprice, int snumber, Integer pid ){
		this.sname = sname;
		this.sprice = sprice;
		this.snumber = snumber;
		this.pid = pid;
	}

	public Integer getSid() {
		return this.sid;
	}

	public void setSid(Integer sid) {
		this.sid = sid;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public BigDecimal getSprice() {
		return this.sprice;
	}

	public void setSprice(BigDecimal sprice) {
		this.sprice = sprice;
	}

	public int getSnumber() {
		return this.snumber;
	}

	public void setSnumber(int snumber) {
		this.snumber = snumber;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}



}
