package com.xy9860.shop.model;
// Generated 2017-3-22 11:18:04 by Hibernate Tools 5.2.1.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer uid;
	private String ulogin;
	private String uname;
	private String upass;
	private String usex;
	private String uphone;
	private String uemail;

	public User() {
	}

	public User(String ulogin, String uname, String upass, String usex, String uphone, String uemail) {
		this.ulogin = ulogin;
		this.uname = uname;
		this.upass = upass;
		this.usex = usex;
		this.uphone = uphone;
		this.uemail = uemail;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUlogin() {
		return this.ulogin;
	}

	public void setUlogin(String ulogin) {
		this.ulogin = ulogin;
	}

	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getUpass() {
		return this.upass;
	}

	public void setUpass(String upass) {
		this.upass = upass;
	}

	public String getUsex() {
		return this.usex;
	}

	public void setUsex(String usex) {
		this.usex = usex;
	}

	public String getUphone() {
		return this.uphone;
	}

	public void setUphone(String uphone) {
		this.uphone = uphone;
	}

	public String getUemail() {
		return this.uemail;
	}

	public void setUemail(String uemail) {
		this.uemail = uemail;
	}

}
